### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by simplylu** [JoshuaSkelly/earcut-python#3]
**Steps to reproduce:**
Install the package from pypi:
`pip3 install earcut`

Import and run example from the README.md file:
```py
>>> import earcut
>>> triangles = earcut([10, 0, 0, 50, 60, 60, 70, 10])
Traceback (most recent call last):
    File "<input>", line 1, in <module>
        earcut([10, 0, 0, 50, 60, 70, 10])
TypeError 'module' object is not callable
```

**Expected output**:
```py
[1, 0, 3, 3, 2, 1]
```

**pip show earcut**
```
Name: earcut
Version: 1.1.4
Summary: A pure Python port of the earcut JS triangulation library
Home-page: https://github.com/MetacitySuite/earcut-python
Author: Metacity
Author-email: 
License: ISC
Location: /home/rtfm/.local/lib/python3.10/site-packages
Requires: numpy
Required-by:
```

The referenced Location discussed in #1 and introduced by @vojtatom is not available any more.

**Comment by simplylu** [comment]
Damn. The solution was:
```py
from earcut.earcut import earcut
```

**Comment by vojtatom** [comment]
Hey, the import structure is a bit unfortunate but I'm glad you got it. I could update it to make it simpler, but I'm deciding whether it's worth it - see https://github.com/joshuaskelly/earcut-python/issues/1
